[package]
name = "infotube"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
tokio = { version = "1.42.0", features = ["full"] }
serde = { version = "1.0.216", features = ["derive"] }
toml = "0.8.19"
anyhow = "1.0.95"
unicode-width = "0.2.0"